package lib.model;

public enum Attribute {
    STYLE_NUMBER,
    STYLE_NONE,
    STYLE_DEFAULT,
    STYLE_PERCENT,
    STYLE_SOLID,
    STYLE_SOLID_NUMBER,
    STYLE_SOLID_PERCENT,
    STYLE_HEADER,

    ALIGN_GENERAL,
    ALIGN_LEFT,
    ALIGN_CENTER,
    ALIGN_RIGHT,
    ALIGN_FILL,
    ALIGN_JUSTIFY,
    ALIGN_CENTER_SELECTION,
    ALIGN_VERTICAL_TOP,
    ALIGN_VERTICAL_CENTER,
    ALIGN_VERTICAL_BOTTOM,
    ALIGN_VERTICAL_JUSTIFY,

    DIRECTION_RTL,
    DIRECTION_LTR
}
